export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const RENAME_SUCCESS = "RENAME_SUCCESS"
export const RENAME_FAIL = "RENAME_FAIL"
export const REPASSWORD_SUCCESS = "REPASSWORD_SUCCESS"
export const REPASSWORD_FAIL = "REPASSWORD_FAIL"

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const PROJECTS_LOADING = 'PROJECTS_LOADING'
export const PROJECTS_LOADED = 'PROJECTS_LOADED'
export const PROJECTS_LOAD_FAIL = 'PROJECTS_LOAD_FAIL'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL'
export const GET_CURRENT_PROJECT_SUCCESS = 'GET_CURRENT_PROJECT_SUCCESS'
export const GET_CURRENT_PROJECT_FAIL = 'GET_CURRENT_PROJECT_FAIL'
export const REMOVE_CURRENT_PROJECT = 'REMOVE_CURRENT_PROJECT'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_FAIL = 'EDIT_PROJECT_FAIL'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL'

export const TICKETS_LOADING = 'TICKETS_LOADING'
export const TICKETS_LOADED = 'TICKETS_LOADED'
export const TICKETS_LOAD_FAIL = 'TICKETS_LOAD_FAIL'
export const CLEAR_TICKETS = 'CLEAR_TICKETS'
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS'
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL'
export const GET_CURRENT_TICKET_SUCCESS = 'GET_CURRENT_TICKET_SUCCESS'
export const GET_CURRENT_TICKET_FAIL = 'GET_CURRENT_TICKET_FAIL'
export const REMOVE_CURRENT_TICKET = 'REMOVE_CURRENT_TICKET'
export const EDIT_TICKET_SUCCESS = 'EDIT_TICKET_SUCCESS'
export const EDIT_TICKET_FAIL = 'EDIT_TICKET_FAIL'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL'

export const COMMENTS_LOADING = 'COMMENTS_LOADING'
export const COMMENTS_LOADED = 'COMMENTS_LOADED'
export const COMMENTS_LOAD_FAIL = 'COMMENTS_LOAD_FAIL'
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'

export const USERS_LOADING = 'USERS_LOADING'
export const USERS_LOADED = 'USERS_LOADED'
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL'
export const SELECT_USER = 'SELECT_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL'
